In [1]:
import pandas as pd

In [4]:
url = 'https://api.covidtracking.com/v1/states/daily.csv'

In [5]:
df = pd.read_csv(url, parse_dates=['date'])

In [6]:
df.head()

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,2021-01-15,AK,49835.0,NaN,1339391.0,NaN,totalTestsViral,1389226.0,77.0,1152.0,...,1389226,1,3,0d6d7a509fe581dba7c140188ff4c9016f79482c,0,0,0,0,0,NaN
1,2021-01-15,AL,417528.0,85443.0,1680128.0,NaN,totalTestsPeopleViral,2012213.0,2863.0,38763.0,...,2097656,85,313,65f7f5ceabbef741fe718e564feec8468d699f4f,0,0,0,0,0,NaN
2,2021-01-15,AR,267635.0,51296.0,2032273.0,NaN,totalTestsViral,2248612.0,1314.0,12598.0,...,2299908,35,95,1475b072612e89caa05010d39a0f687a77b9cf4b,0,0,0,0,0,NaN
3,2021-01-15,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,2140,0,0,69cae2d608316cfd548a55eff63c4061d569a705,0,0,0,0,0,NaN
4,2021-01-15,AZ,658186.0,36409.0,2552128.0,NaN,totalTestsViral,5912271.0,4866.0,45665.0,...,3210314,185,405,87160dcbe7cfbaff9fa4e15320b291abde58afde,0,0,0,0,0,NaN

In [7]:
df.columns

Index(['date', 'state', 'positive', 'probableCases', 'negative', 'pending',
       'totalTestResultsSource', 'totalTestResults', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'dataQualityGrade', 'lastUpdateEt', 'dateModified', 'checkTimeEt',
       'death', 'hospitalized', 'dateChecked', 'totalTestsViral',
       'positiveTestsViral', 'negativeTestsViral', 'positiveCasesViral',
       'deathConfirmed', 'deathProbable', 'totalTestEncountersViral',
       'totalTestsPeopleViral', 'totalTestsAntibody', 'positiveTestsAntibody',
       'negativeTestsAntibody', 'totalTestsPeopleAntibody',
       'positiveTestsPeopleAntibody', 'negativeTestsPeopleAntibody',
       'totalTestsPeopleAntigen', 'positiveTestsPeopleAntigen',
       'totalTestsAntigen', 'positiveTestsAntigen', 'fips', 'positiveIncrease',
       'negativeIncrease', 'total', 'totalTestResultsIncrease', 'posNeg',
       'deathIncrease', 'hospitalizedIncrease', 'hash', 'commercialScore',
       'negativeRegularScore', 'negativeScore', 'positiveScore', 'score',
       'grade'],
      dtype='object')

In [29]:
df[['date', 'state', 'positive']].sort_values(by='date')

            date state  positive
17913 2020-01-13    WA       NaN
17912 2020-01-14    WA       0.0
17911 2020-01-15    WA       0.0
17910 2020-01-16    WA       0.0
17909 2020-01-17    WA       0.0
...          ...   ...       ...
32    2021-01-15    NE  180131.0
31    2021-01-15    ND   95599.0
30    2021-01-15    NC  659840.0
28    2021-01-15    MS  248189.0
0     2021-01-15    AK   49835.0

[17914 rows x 3 columns]

In [ ]:
df.col